site_name: iqoptionapi document
repo_name: "iqoptionapi"
repo_url: "https://github.com/iqoptionapi/iqoptionapi"
site_url: "https://iqoptionapi.github.io/iqoptionapi/"
docs_dir: "doc/"
site_dir: "docs/"
extra:
  search:
    language: "pt-br"
    #-tokenizer: '[\a\-\.]+'
  social:
    - type: "github"
      link: "https://github.com/iqoptionapi/iqoptionapi"

plugins:
  - search:
      lang:
        - pt
        - en
        - es
theme:
  language: "en"
  name: "material" #readthedocs/readthedocs
  palette:
    primary: "indigo"
    accent: "Blue Grey"
  feature:
    tabs: false
  font:
    text: "Roboto"
    code: "Roboto Mono"
  favicon: image/icon/iq.ico

# Extensions
markdown_extensions:
  - footnotes
  - codehilite
  - markdown.extensions.admonition
  #  - markdown.extensions.codehilite:
  #     guess_lang: false
  #     linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details

  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - "javascripts/extra.js"
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js"

nav:
  - Language: index.md
  - EN - Get Start: en/index.md
  - EN - account: en/account/account.md
  - EN - for all: en/all/all.md
  - EN - binary option: en/binary option/binary option.md
  - EN - digital: en/digital/digital.md
  - EN - foreign exchange futures: en/fef/fef.md
  - EN - candle: en/candle/candle.md
  - EN - Techincal Analysis: en/techinical analysis/index.md
